// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPTSobj.InfrastructureServices.Gateways.Database;

namespace ManagementOrganizations.WebService.Migrations
{
    [DbContext(typeof(RPTSobjContext))]
    partial class RPTSobjContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RPTSobj.DomainObjects.RPTSobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetroLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetroStation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RPTSobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Кремль",
                            MetroLine = "Сокольническая линия",
                            MetroStation = "Библиотека имени Ленина",
                            Name = "Успенский собор",
                            WebSite = "http://assumption-cathedral.kreml.ru/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
