// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPTSobj.InfrastructureServices.Gateways.Database;

namespace RPTSobj.WebService.Migrations
{
    [DbContext(typeof(RPTSobjContext))]
    [Migration("20200603184436_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("RPTSobj.DomainObjects.rptsobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetroLine")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetroStation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebSite")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RPTSobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "Кремль",
                            MetroLine = "Сокольническая линия",
                            MetroStation = "Библиотека имени Ленина",
                            Name = "Успенский собор",
                            WebSite = "http://assumption-cathedral.kreml.ru/"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "Кремль",
                            MetroLine = "Сокольническая линия",
                            MetroStation = "Библиотека имени Ленина",
                            Name = "Архангельский собор",
                            WebSite = "http://archangel-cathedral.kreml.ru/"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "Кремль",
                            MetroLine = "Сокольническая линия",
                            MetroStation = "Библиотека имени Ленина",
                            Name = "Благовещенский собор",
                            WebSite = "http://annunciation-cathedral.kreml.ru/"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "Кремль",
                            MetroLine = "Сокольническая линия",
                            MetroStation = "Библиотека имени Ленина",
                            Name = "Патриаршие палаты с церковью Двенадцати апостолов",
                            WebSite = "http://www.kreml.ru/visit-to-kremlin/what-to-see/patriarshie-palaty-s-tserkovyu-dvenadtsati-apostolov"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
